## src/Source/BUILD

cc_library(
    name = "AuthorsList",
    srcs = ["authorsList.cpp"],
    hdrs = ["authorsList.hpp"],
    deps = ["//src/Author:Author"],
    visibility = ["//visibility:public"],
)
