## src/Source/BUILD

cc_library(
    name = "Person",
    srcs = ["Person.cpp", "Student.cpp", "Professor.cpp"],
    hdrs = ["Person.hpp", "Student.hpp", "Professor.hpp"],
    visibility = ["//visibility:public"],
)
