## src/tests/BUILD

cc_test(
    name = "test",
    srcs = ["tests.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/Source:func",
    ],
    data = [
        "//src/files:data",
    ]
)
