## src/Source/BUILD

cc_library(
    name = "Source",
    srcs = ["Student.cpp", "StudentFirstSession.cpp", "StudentYear.cpp"],
    hdrs = ["Student.hpp", "StudentFirstSession.hpp", "StudentYear.hpp"],
    visibility = ["//visibility:public"],
)
