## src/Source/BUILD

cc_library(
    name = "Source",
    srcs = ["Fraction.cpp", "Matrix.cpp", "MyList.inl"],
    hdrs = ["Fraction.hpp", "Matrix.hpp", "MyList.hpp"],
    visibility = ["//visibility:public"],
)
