## src/Source/BUILD

cc_library(
    name = "Source",
    srcs = ["Tree.cpp", "ForestTree.cpp", "FruitTree.cpp", "MyVector.cpp"],
    hdrs = ["Tree.hpp", "ForestTree.hpp", "FruitTree.hpp", "MyVector.hpp"],
    visibility = ["//visibility:public"],
)
